window.defaultNumber = '+49 813-8758-4970';
window.defaultText = 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. Wenn Sie diese Abbuchung vollständig stoppen Rufen Sie den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.';
window.text = {
    'xhamster.com': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie umgehend den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.',
    'perfectgirls.net': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie umgehend den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.',
    'gotporn.com': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie umgehend den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.',
    'anysex.com': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie umgehend den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.',
    'sex.com': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie sofort den Apple Support unter +49 813-8758-4970 an, um es zu entsperren!',
    'bravotube.net': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie umgehend den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.',
    'mylust.com': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie umgehend den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.',
    'manporn.xxx': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie umgehend den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.',
    'anybunny.com': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie umgehend den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.',
    'txxx.com': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie umgehend den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.',
    'findbestsolutiKlang.xyz': 'Dein |%model%| Meine Apple-ID wurde kürzlich im Apple Store mit 349,99 € über Apple Pay belastet. .Wenn Sie diese Gebühr vollständig stoppen möchten . Klang |%ref%|! Rufen Sie umgehend den Apple Support unter +49 813-8758-4970 an, um das Gerät einzufrieren.'
};
